services:
  db:
    image: postgres:15-alpine
    container_name: fintech-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fintech-network

  app:
    build: .
    container_name: fintech-app
    env_file:
      - .env
    environment:
      # Only override the host to point to the db service
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./Local_file:/app/Local_file
    networks:
      - fintech-network

volumes:
  db_data:

networks:
  fintech-network:
    driver: bridge