version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: fintech-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fintech-network

  app:
    build: .
    container_name: fintech-app
    env_file:
      - .env
    environment:
      DB_HOST: db
      # Container path for reports (internal to container)
      REPORT_OUTPUT_DIR: /app/reports
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # Map host folder (from .env) to container folder inside app
      - ${REPORT_OUTPUT_DIR}:/app/reports
    networks:
      - fintech-network

volumes:
  db_data:

networks:
  fintech-network:
